/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rup;

import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.openqa.selenium.WebDriver;
import static rup.LabelImage.path;

/**
 *
 * @author mahe
 */
public class personalpage extends javax.swing.JFrame {
private static WebDriver driver;
    /**
     * Creates new form personalpage
     */
    public personalpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        desp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        avg_rate = new javax.swing.JLabel();
        imdb = new javax.swing.JLabel();
        num_view = new javax.swing.JLabel();
        hyp = new javax.swing.JLabel();
        panels = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        rb5 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        rb6 = new javax.swing.JRadioButton();
        rb7 = new javax.swing.JRadioButton();
        rb8 = new javax.swing.JRadioButton();
        rb9 = new javax.swing.JRadioButton();
        rb10 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        desp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("BOOK THE TICKETS");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("GO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("AVERAGE RATINGS");

        lb1.setText("Photo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("NO OF REVIEWERS");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("IMDB Rating");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("SHORT DESCRIPTION");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("ADD TO WATCHLIST");

        avg_rate.setText("jLabel13");

        imdb.setText("jLabel1");

        num_view.setText("jLabel5");

        hyp.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        hyp.setText("RATE MY SHOW");
        hyp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hypMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hypMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hypMouseExited(evt);
            }
        });

        panels.setLayout(new java.awt.GridBagLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("RECOMMEND YOUR FRIENDS");

        buttonGroup3.add(jCheckBox5);
        jCheckBox5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox5.setText("YES");

        buttonGroup3.add(jCheckBox6);
        jCheckBox6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox6.setText("NOT NOW");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("RATE THE MOVIE");

        rb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rb1MouseEntered(evt);
            }
        });

        rb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rb2MouseEntered(evt);
            }
        });

        rb3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rb3MouseEntered(evt);
            }
        });

        rb4.setName(""); // NOI18N
        rb4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rb4MouseEntered(evt);
            }
        });

        rb5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rb5MouseEntered(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("SUBMIT ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jCheckBox3);
        jCheckBox3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox3.setText("YES");

        buttonGroup2.add(jCheckBox4);
        jCheckBox4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox4.setText("LATER");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("WANT TO RATE THIS MOVIE");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("ALREADY WATCHED ?");

        buttonGroup1.add(jCheckBox1);
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox1.setText("YES");

        buttonGroup1.add(jCheckBox2);
        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBox2.setText("NO");

        rb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hyp, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(33, 33, 33)
                                        .addComponent(num_view, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(62, 62, 62)
                                        .addComponent(imdb, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(28, 28, 28)
                                        .addComponent(avg_rate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(desp, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel8)
                        .addGap(78, 78, 78)
                        .addComponent(jCheckBox1)
                        .addGap(90, 90, 90)
                        .addComponent(jCheckBox2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel11)
                        .addGap(19, 19, 19)
                        .addComponent(jCheckBox5)
                        .addGap(113, 113, 113)
                        .addComponent(jCheckBox6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel12)
                        .addGap(70, 70, 70)
                        .addComponent(jButton2)
                        .addGap(109, 109, 109)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(44, 44, 44)
                                .addComponent(jCheckBox3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(81, 81, 81)
                                .addComponent(rb1)
                                .addGap(2, 2, 2)
                                .addComponent(rb2)
                                .addGap(2, 2, 2)
                                .addComponent(rb3)
                                .addGap(2, 2, 2)
                                .addComponent(rb4)
                                .addGap(2, 2, 2)
                                .addComponent(rb5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jCheckBox4))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb10)
                                .addGap(43, 43, 43)
                                .addComponent(jButton1)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hyp)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel2))
                            .addComponent(num_view, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel3))
                            .addComponent(imdb, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel6))
                            .addComponent(avg_rate, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addComponent(jLabel7)
                .addGap(11, 11, 11)
                .addComponent(desp, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel8))
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jCheckBox3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jCheckBox4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(rb1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(rb2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(rb3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(rb4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(rb5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb7)
                            .addComponent(rb6)
                            .addComponent(rb8)
                            .addComponent(rb9)
                            .addComponent(rb10)
                            .addComponent(jButton1))))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel11))
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox6))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel12))
                    .addComponent(jButton2)
                    .addComponent(jButton3)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
String movie_name;
double avgs ;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        Icon src = new ImageIcon(new ImageIcon(LabelImage.path).getImage().getScaledInstance(lb1.getWidth(), lb1.getHeight(), Image.SCALE_SMOOTH));
        LabelImage.src=src;
        lb1.setIcon(LabelImage.src); 
        
        if(Basic.login==1)
            panels.setVisible(true);
        else
            panels.setVisible(false);
        
        desp.setEditable(false);   
        desp.setEnabled(false);
        desp.setDisabledTextColor(Color.BLACK);//description text area
        setExtendedState(this.MAXIMIZED_BOTH);
        
    try{          //Connection Code 
       Connection conn = Conn.connect();                                                             
       PreparedStatement pst =   conn.prepareStatement("Select * from movie_details where movie_id= "+LabelImage.id+";");
       ResultSet rs = pst.executeQuery();    
       //conn.close();
       if(rs.next()){
           movie_name = rs.getString("movie_name");
           String movie_desc = rs.getString("about_movie");
           avgs = rs.getDouble("avg_rating");
           int num = rs.getInt("no_of_reviews");
           desp.setText(movie_desc);
            num_view.setText(num+"");
            avg_rate.setText(avgs+"");
       }
       
       
   }
   catch(Exception e){
       e.printStackTrace();
      // return false;
   }
    }//GEN-LAST:event_formWindowOpened

    private void despActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_despActionPerformed

    private void rb1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb1MouseEntered
       rb1.setSelected(true);
       rb2.setSelected(false);
       rb3.setSelected(false);
       rb4.setSelected(false);
       rb5.setSelected(false);
       rb6.setSelected(false);
       rb7.setSelected(false);
       rb8.setSelected(false);
       rb9.setSelected(false);
       rb10.setSelected(false);
    }//GEN-LAST:event_rb1MouseEntered

    private void rb2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb2MouseEntered
rb1.setSelected(true);
       rb2.setSelected(true);
       rb3.setSelected(false);
       rb4.setSelected(false);
       rb5.setSelected(false);  
       rb6.setSelected(false);
       rb7.setSelected(false);
       rb8.setSelected(false);
       rb9.setSelected(false);
       rb10.setSelected(false);
    }//GEN-LAST:event_rb2MouseEntered

    private void rb3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb3MouseEntered
rb1.setSelected(true);
       rb2.setSelected(true);
       rb3.setSelected(true);
       rb4.setSelected(false);
       rb5.setSelected(false); 
rb6.setSelected(false);
       rb7.setSelected(false);
       rb8.setSelected(false);
       rb9.setSelected(false);
       rb10.setSelected(false);      // TODO add your handling code here:
    }//GEN-LAST:event_rb3MouseEntered

    private void rb4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb4MouseEntered
rb1.setSelected(true);
       rb2.setSelected(true);
       rb3.setSelected(true);
       rb4.setSelected(true);
       rb5.setSelected(false); 
       rb6.setSelected(false);
       rb7.setSelected(false);
       rb8.setSelected(false);
       rb9.setSelected(false);
       rb10.setSelected(false);      // TODO add your handling code here:
    }//GEN-LAST:event_rb4MouseEntered

    private void rb5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb5MouseEntered
rb1.setSelected(true);
       rb2.setSelected(true);
       rb3.setSelected(true);
       rb4.setSelected(true);
       rb5.setSelected(true);   
       rb6.setSelected(false);
       rb7.setSelected(false);
       rb8.setSelected(false);
       rb9.setSelected(false);
       rb10.setSelected(false);
    }//GEN-LAST:event_rb5MouseEntered

private void rb6MouseEntered(java.awt.event.MouseEvent evt) {                                 
rb1.setSelected(true);
       rb2.setSelected(true);
       rb3.setSelected(true);
       rb4.setSelected(true);
       rb5.setSelected(true);   
       rb6.setSelected(true);
       rb7.setSelected(false);
       rb8.setSelected(false);
       rb9.setSelected(false);
       rb10.setSelected(false);
    }

private void rb7MouseEntered(java.awt.event.MouseEvent evt) {                                 
rb1.setSelected(true);
       rb2.setSelected(true);
       rb3.setSelected(true);
       rb4.setSelected(true);
       rb5.setSelected(true);   
       rb6.setSelected(true);
       rb7.setSelected(true);
       rb8.setSelected(false);
       rb9.setSelected(false);
       rb10.setSelected(false);
    }

private void rb8MouseEntered(java.awt.event.MouseEvent evt) {                                 
rb1.setSelected(true);
       rb2.setSelected(true);
       rb3.setSelected(true);
       rb4.setSelected(true);
       rb5.setSelected(true);   
       rb6.setSelected(true);
       rb7.setSelected(true);
       rb8.setSelected(true);
       rb9.setSelected(false);
       rb10.setSelected(false);
    }
private void rb9MouseEntered(java.awt.event.MouseEvent evt) {                                 
rb1.setSelected(true);
       rb2.setSelected(true);
       rb3.setSelected(true);
       rb4.setSelected(true);
       rb5.setSelected(true);   
       rb6.setSelected(true);
       rb7.setSelected(true);
       rb8.setSelected(true);
       rb9.setSelected(true);
       rb10.setSelected(false); 
    }

private void rb10MouseEntered(java.awt.event.MouseEvent evt){                                 
rb1.setSelected(true);
       rb2.setSelected(true);
       rb3.setSelected(true);
       rb4.setSelected(true);
       rb5.setSelected(true);   
       rb6.setSelected(true);
       rb7.setSelected(true);
       rb8.setSelected(true);
       rb9.setSelected(true);
       rb10.setSelected(true);
    }
    private void hypMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hypMouseClicked
this.setVisible(false);
new mainForm().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_hypMouseClicked

    private void hypMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hypMouseEntered
hyp.setForeground(Color.RED);        // TODO add your handling code here:
    }//GEN-LAST:event_hypMouseEntered

    private void hypMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hypMouseExited
hyp.setForeground(Color.BLACK);        // TODO add your handling code here:
    }//GEN-LAST:event_hypMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        System.setProperty("webdriver.chrome.driver","C:\\Users\\mahe\\Desktop\\chromedriver.exe");
    driver = new ChromeDriver();
    Dimension d;
      d = new Dimension(0,0);
   driver.manage().window().maximize();
    driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
    try{
       // InputStream ExcelFileToRead = new FileInputStream("C:\\Users\\mahe\\Desktop\\automation.xlsx");
//        XSSFWorkbook  wb1 = new XSSFWorkbook(ExcelFileToRead);
//	XSSFSheet sheetInp = wb1.getSheetAt(0);
//        String loc = sheetInp.getRow(1).getCell(0).getStringCellValue();
        String loc = "https://in.bookmyshow.com/manipal";
	driver.get(loc);       
        //Thread.sleep(3000);
        //driver.findElement(By.xpath("//*[@id=\"wzrk-cancel\"]"));
        driver.findElement(By.xpath("//*[@id=\"quickbook-wrapper\"]/div[1]/div[1]/span[1]/input[2]")).sendKeys(movie_name);
        driver.findElement(By.xpath("//*[@id=\"wzrk-cancel\"]")).click();
        driver.findElement(By.xpath("//*[@id=\"quickbook-wrapper\"]/div[1]/div[1]/span[1]/input[2]")).click();
        driver.findElement(By.xpath("//*[@id=\"quickbook-wrapper\"]/div[1]/div[1]/span[1]/div/div/div[2]")).click();
        }
	catch (Exception e)
	{
        String message = e.getMessage();
        System.out.println("Error"+message);
	}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int val=0;
        if(rb1.isSelected())
            val=1;
        else if(rb2.isSelected())
            val=2;
        else if(rb3.isSelected())
            val=3;
        else if(rb4.isSelected())
            val=4;
        else if(rb5.isSelected())
            val=5;
        else if(rb5.isSelected())
            val=5;
        else if(rb5.isSelected())
            val=5;
        else if(rb5.isSelected())
            val=5;
        else if(rb5.isSelected())
            val=5;
        else if(rb5.isSelected())
            val=5;
        double art=(val+avgs)/2;
        avg_rate.setText(art+"");
        Connection conn = Conn.connect();
        PreparedStatement pst;
    try {
        pst = conn.prepareStatement("update movie_details set avg_rating="+art+" where movie_id="+LabelImage.id+";");
        pst.execute();
    } catch (SQLException ex) {
        Logger.getLogger(personalpage.class.getName()).log(Level.SEVERE, null, ex);
    }
        JOptionPane.showMessageDialog(null,"Thank you");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(personalpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(personalpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(personalpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(personalpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new personalpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avg_rate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JTextField desp;
    private javax.swing.JLabel hyp;
    private javax.swing.JLabel imdb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel num_view;
    private javax.swing.JPanel panels;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb10;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JRadioButton rb6;
    private javax.swing.JRadioButton rb7;
    private javax.swing.JRadioButton rb8;
    private javax.swing.JRadioButton rb9;
    // End of variables declaration//GEN-END:variables
}
